name: Update README with Latest GitHub Repos

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with latest GitHub repos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 5
          feed_list: "https://github.com/trijesh61.atom"
